/**
 * Tests for applyImportedStores sanitize pass (F13).
 * Verify: segments/equipment missing required fields get defaults after import.
 */

import { beforeEach, describe, it, expect } from 'vitest'
import { applyImportedStores } from './importService'
import { useSystemStore } from '../store/systemStore'
import { useSegmentStore } from '../store/segmentStore'
import { useEquipmentStore } from '../store/equipmentStore'
import { useEnclosureStore } from '../store/enclosureStore'

type SegmentLike = {
  id: string
  systemId?: string
  kind?: string
  autoGenerated?: boolean
  [k: string]: unknown
}

beforeEach(() => {
  useSystemStore.setState({ systems: {}, systemOrder: [] })
  useSegmentStore.setState({ segments: {}, segmentOrder: [] })
  useEquipmentStore.setState({ equipment: {}, equipmentOrder: [] })
  useEnclosureStore.setState({ enclosures: {}, enclosureOrder: [] })
})

describe('applyImportedStores — sanitize (F13)', () => {
  it('сегмент без systemId получает id первой системы', () => {
    const sysId = useSystemStore.getState().addSystem({
      name: 'Система 1', schemaType: 'two-pipe-dead-end',
      pipeMaterialId: 'pe-x-16-2', coolantId: 'water',
      tSupply: 80, tReturn: 60, tSupplyUfh: 45, tReturnUfh: 35, sourceLabel: '',
    })

    applyImportedStores({
      segments: {
        'seg-1': {
          id: 'seg-1', parentSegmentId: null, name: 'Магистраль',
          equipmentId: null, qOverride: null, lengthM: 5,
          pipeId: 'pe-x-16-2', dnMm: null, kmsCounts: {}, velocityTargetMS: 0.6,
          // no systemId, kind, autoGenerated
        },
      },
      segmentOrder: ['seg-1'],
    })

    const seg = useSegmentStore.getState().segments['seg-1'] as unknown as SegmentLike
    expect(seg).toBeDefined()
    expect(seg.systemId).toBe(sysId)
    expect(seg.kind).toBe('branch')
    expect(seg.autoGenerated).toBe(false)
  })

  it('сегмент с пустым systemId=«» получает id первой системы', () => {
    const sysId = useSystemStore.getState().addSystem({
      name: 'Система 1', schemaType: 'two-pipe-dead-end',
      pipeMaterialId: 'pe-x-16-2', coolantId: 'water',
      tSupply: 80, tReturn: 60, tSupplyUfh: 45, tReturnUfh: 35, sourceLabel: '',
    })

    applyImportedStores({
      segments: {
        'seg-1': {
          id: 'seg-1', parentSegmentId: null, name: 'Стояк',
          equipmentId: null, qOverride: null, lengthM: 3,
          pipeId: 'pe-x-16-2', dnMm: null, kmsCounts: {}, velocityTargetMS: 0.6,
          systemId: '',  // explicitly empty
          kind: 'riser',
          autoGenerated: true,
        },
      },
      segmentOrder: ['seg-1'],
    })

    const seg = useSegmentStore.getState().segments['seg-1'] as unknown as SegmentLike
    expect(seg.systemId).toBe(sysId)
    expect(seg.kind).toBe('riser')  // valid kind → preserved
    expect(seg.autoGenerated).toBe(true)  // existing boolean → preserved
  })

  it('сегмент с неизвестным kind получает kind=«branch»', () => {
    applyImportedStores({
      segments: {
        'seg-1': {
          id: 'seg-1', parentSegmentId: null, name: 'Х',
          equipmentId: null, qOverride: null, lengthM: 1,
          pipeId: 'pe-x-16-2', dnMm: null, kmsCounts: {}, velocityTargetMS: 0.6,
          kind: 'unknown-type',
        },
      },
      segmentOrder: ['seg-1'],
    })

    const seg = useSegmentStore.getState().segments['seg-1'] as unknown as SegmentLike
    expect(seg.kind).toBe('branch')
  })

  it('оборудование без systemId получает id первой системы', () => {
    const sysId = useSystemStore.getState().addSystem({
      name: 'Система 1', schemaType: 'two-pipe-dead-end',
      pipeMaterialId: 'pe-x-16-2', coolantId: 'water',
      tSupply: 80, tReturn: 60, tSupplyUfh: 45, tReturnUfh: 35, sourceLabel: '',
    })

    applyImportedStores({
      equipment: {
        'eq-1': {
          id: 'eq-1', roomId: 'r1',
          kind: 'bimetal', catalogModelId: null, connection: 'side',
          installation: 'open', panelType: null, panelHeightMm: null,
          panelLengthMm: null, sectionsOverride: null,
          convectorLengthMm: null, manualQNominal: null, manualNExponent: null,
          // no systemId
        },
      },
      equipmentOrder: ['eq-1'],
    })

    const eq = useEquipmentStore.getState().equipment['eq-1'] as unknown as { systemId: string }
    expect(eq).toBeDefined()
    expect(eq.systemId).toBe(sysId)
  })

  it('оборудование с корректным systemId сохраняет его', () => {
    const sysId = useSystemStore.getState().addSystem({
      name: 'Система 1', schemaType: 'two-pipe-dead-end',
      pipeMaterialId: 'pe-x-16-2', coolantId: 'water',
      tSupply: 80, tReturn: 60, tSupplyUfh: 45, tReturnUfh: 35, sourceLabel: '',
    })

    applyImportedStores({
      equipment: {
        'eq-1': {
          id: 'eq-1', roomId: 'r1',
          systemId: sysId,  // valid id — must be preserved
          kind: 'bimetal', catalogModelId: null, connection: 'side',
          installation: 'open', panelType: null, panelHeightMm: null,
          panelLengthMm: null, sectionsOverride: null,
          convectorLengthMm: null, manualQNominal: null, manualNExponent: null,
        },
      },
      equipmentOrder: ['eq-1'],
    })

    const eq = useEquipmentStore.getState().equipment['eq-1'] as unknown as { systemId: string }
    expect(eq.systemId).toBe(sysId)
  })
})
