/**
 * Cross-store apply for imported project data.
 * Decouples projectStore.importJSON from direct setState calls on other stores.
 */

import { useSystemStore } from '../store/systemStore'
import { useSegmentStore } from '../store/segmentStore'
import { useEquipmentStore } from '../store/equipmentStore'
import { useUfhLoopStore } from '../store/ufhLoopStore'
import { useEnclosureStore } from '../store/enclosureStore'
import { shapeMerge } from '../store/safeStorage'
import { toast } from 'sonner'

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

export function applyImportedStores(data: Record<string, unknown>): void {
  if (data.enclosures !== undefined) {
    if (!isPlainObject(data.enclosures)) {
      console.warn('[importService] skipped enclosures: not a plain object')
    } else {
      const validated = shapeMerge(
        { enclosures: data.enclosures, enclosureOrder: data.enclosureOrder },
        { enclosures: {} as Record<string, never>, enclosureOrder: [] as string[] },
        { enclosures: 'record', enclosureOrder: 'array-of-string' }
      )
      useEnclosureStore.setState({ enclosures: validated.enclosures, enclosureOrder: validated.enclosureOrder })
    }
  }

  if (data.systems !== undefined) {
    if (!isPlainObject(data.systems)) {
      console.warn('[importService] skipped systems: not a plain object')
    } else {
      const validated = shapeMerge(
        { systems: data.systems, systemOrder: data.systemOrder },
        { systems: {} as Record<string, never>, systemOrder: [] as string[] },
        { systems: 'record', systemOrder: 'array-of-string' }
      )
      useSystemStore.setState({ systems: validated.systems, systemOrder: validated.systemOrder })
    }
  }

  // Fallback system id for sanitizing segments/equipment missing systemId.
  // Systems are already set above (if present in data), so this reads the current state.
  const firstSystemId = useSystemStore.getState().systemOrder[0] ?? ''

  const SEGMENT_KINDS = new Set(['trunk', 'riser', 'branch', 'connection'])

  if (data.segments !== undefined) {
    if (!isPlainObject(data.segments)) {
      console.warn('[importService] skipped segments: not a plain object')
    } else {
      const validated = shapeMerge(
        { segments: data.segments, segmentOrder: data.segmentOrder },
        { segments: {} as Record<string, never>, segmentOrder: [] as string[] },
        { segments: 'record', segmentOrder: 'array-of-string' }
      )
      const sanitized: Record<string, unknown> = {}
      for (const [id, seg] of Object.entries(validated.segments as Record<string, unknown>)) {
        if (typeof seg !== 'object' || seg === null) { sanitized[id] = seg; continue }
        const s = seg as Record<string, unknown>
        sanitized[id] = {
          ...s,
          systemId: typeof s.systemId === 'string' && s.systemId ? s.systemId : firstSystemId,
          kind: SEGMENT_KINDS.has(s.kind as string) ? s.kind : 'branch',
          autoGenerated: typeof s.autoGenerated === 'boolean' ? s.autoGenerated : false,
        }
      }
      useSegmentStore.setState({ segments: sanitized as Record<string, never>, segmentOrder: validated.segmentOrder })
    }
  }

  if (data.equipment !== undefined) {
    if (!isPlainObject(data.equipment)) {
      console.warn('[importService] skipped equipment: not a plain object')
    } else {
      const validated = shapeMerge(
        { equipment: data.equipment, equipmentOrder: data.equipmentOrder },
        { equipment: {} as Record<string, never>, equipmentOrder: [] as string[] },
        { equipment: 'record', equipmentOrder: 'array-of-string' }
      )
      const sanitized: Record<string, unknown> = {}
      for (const [id, eq] of Object.entries(validated.equipment as Record<string, unknown>)) {
        if (typeof eq !== 'object' || eq === null) { sanitized[id] = eq; continue }
        const e = eq as Record<string, unknown>
        sanitized[id] = {
          ...e,
          systemId: typeof e.systemId === 'string' && e.systemId ? e.systemId : firstSystemId,
        }
      }
      useEquipmentStore.setState({ equipment: sanitized as Record<string, never>, equipmentOrder: validated.equipmentOrder })
    }
  }

  if (data.ufhLoops !== undefined) {
    if (!isPlainObject(data.ufhLoops)) {
      console.warn('[importService] skipped ufhLoops: not a plain object')
    } else {
      const loopsRaw = data.ufhLoops as Record<string, { id?: string; roomId?: string }>
      const loopsByRoom: Record<string, string> = {}
      for (const [id, loop] of Object.entries(loopsRaw)) {
        if (loop && typeof loop === 'object' && typeof loop.roomId === 'string') {
          loopsByRoom[loop.roomId] = id
        }
      }
      useUfhLoopStore.setState({
        loops: loopsRaw,
        loopsByRoom
      } as unknown as Parameters<typeof useUfhLoopStore.setState>[0])
    }
  }
}
