import { describe, it, expect, beforeEach } from 'vitest'
import { useSegmentStore, selectSegmentsByParent } from './segmentStore'
import type { Segment } from '../types/hydraulics'

const makeSegment = (overrides: Partial<Omit<Segment, 'id'>> = {}): Omit<Segment, 'id'> => ({
  parentSegmentId: null,
  name: 'Магистраль 1',
  equipmentId: null,
  qOverride: null,
  lengthM: 10,
  pipeId: 'steel-vgp-dn20',
  dnMm: 20,
  kmsCounts: {},
  velocityTargetMS: 0.6,
  // Phase 04.1 required fields
  systemId: 'sys-1',
  kind: 'trunk',
  autoGenerated: false,
  ...overrides
})

beforeEach(() => {
  useSegmentStore.setState({ segments: {}, segmentOrder: [] })
  localStorage.clear()
})

describe('useSegmentStore', () => {
  describe('addSegment', () => {
    it('Test 1: returns id, adds to segmentOrder', () => {
      const id = useSegmentStore.getState().addSegment(makeSegment())
      const state = useSegmentStore.getState()
      expect(typeof id).toBe('string')
      expect(id.length).toBeGreaterThan(0)
      expect(state.segmentOrder).toContain(id)
      expect(state.segments[id]).toBeDefined()
      expect(state.segments[id].name).toBe('Магистраль 1')
    })

    it('multiple adds append to segmentOrder in order', () => {
      const id1 = useSegmentStore.getState().addSegment(makeSegment({ name: 'Seg 1' }))
      const id2 = useSegmentStore.getState().addSegment(makeSegment({ name: 'Seg 2' }))
      const id3 = useSegmentStore.getState().addSegment(makeSegment({ name: 'Seg 3' }))
      expect(useSegmentStore.getState().segmentOrder).toEqual([id1, id2, id3])
    })

    it('stores systemId/kind/autoGenerated from input', () => {
      const id = useSegmentStore.getState().addSegment(makeSegment({ systemId: 'sys-abc', kind: 'riser', autoGenerated: true }))
      const seg = useSegmentStore.getState().segments[id]
      expect(seg.systemId).toBe('sys-abc')
      expect(seg.kind).toBe('riser')
      expect(seg.autoGenerated).toBe(true)
    })
  })

  describe('updateSegment', () => {
    it('Test 2: partial update preserves other fields, returns true on success', () => {
      const id = useSegmentStore.getState().addSegment(makeSegment({ lengthM: 5 }))
      const result = useSegmentStore.getState().updateSegment(id, { name: 'Стояк 1' })
      expect(result).toBe(true)
      const seg = useSegmentStore.getState().segments[id]
      expect(seg.name).toBe('Стояк 1')
      expect(seg.lengthM).toBe(5)
      expect(seg.pipeId).toBe('steel-vgp-dn20')
    })

    it('returns false for nonexistent id', () => {
      const result = useSegmentStore.getState().updateSegment('nonexistent', { name: 'X' })
      expect(result).toBe(false)
    })

    it('D-09: returns false on cross-system parent (parent in different system)', () => {
      const parentId = useSegmentStore.getState().addSegment(makeSegment({ systemId: 'sys-A', name: 'Parent' }))
      const childId = useSegmentStore.getState().addSegment(makeSegment({ systemId: 'sys-B', name: 'Child' }))
      // Trying to set parent from sys-A as parent of child in sys-B
      const result = useSegmentStore.getState().updateSegment(childId, { parentSegmentId: parentId })
      expect(result).toBe(false)
      // State unchanged
      expect(useSegmentStore.getState().segments[childId].parentSegmentId).toBeNull()
    })

    it('D-09: allows same-system parent', () => {
      const parentId = useSegmentStore.getState().addSegment(makeSegment({ systemId: 'sys-A', name: 'Parent' }))
      const childId = useSegmentStore.getState().addSegment(makeSegment({ systemId: 'sys-A', name: 'Child' }))
      const result = useSegmentStore.getState().updateSegment(childId, { parentSegmentId: parentId })
      expect(result).toBe(true)
      expect(useSegmentStore.getState().segments[childId].parentSegmentId).toBe(parentId)
    })

    it('D-09: returns false on self-parent', () => {
      const id = useSegmentStore.getState().addSegment(makeSegment())
      const result = useSegmentStore.getState().updateSegment(id, { parentSegmentId: id })
      expect(result).toBe(false)
      expect(useSegmentStore.getState().segments[id].parentSegmentId).toBeNull()
    })

    it('D-21: resets autoGenerated=false on user edit', () => {
      const id = useSegmentStore.getState().addSegment(makeSegment({ autoGenerated: true }))
      useSegmentStore.getState().updateSegment(id, { name: 'Edited' })
      expect(useSegmentStore.getState().segments[id].autoGenerated).toBe(false)
    })

    it('D-21: programmatic systemId-only update does NOT reset autoGenerated', () => {
      const id = useSegmentStore.getState().addSegment(makeSegment({ autoGenerated: true }))
      useSegmentStore.getState().updateSegment(id, { systemId: 'sys-new' })
      expect(useSegmentStore.getState().segments[id].autoGenerated).toBe(true)
    })

    it('D-06: updates velocityTargetMS when kind changes and velocity matches old default', () => {
      const id = useSegmentStore.getState().addSegment(makeSegment({ kind: 'trunk', velocityTargetMS: 0.8 }))
      useSegmentStore.getState().updateSegment(id, { kind: 'riser' })
      expect(useSegmentStore.getState().segments[id].velocityTargetMS).toBe(0.5)
    })

    it('D-06: does NOT update velocity if user already overrode it', () => {
      const id = useSegmentStore.getState().addSegment(makeSegment({ kind: 'trunk', velocityTargetMS: 1.2 }))
      useSegmentStore.getState().updateSegment(id, { kind: 'riser' })
      // velocity was custom (1.2 != trunk default 0.8) — should not be touched
      expect(useSegmentStore.getState().segments[id].velocityTargetMS).toBe(1.2)
    })
  })

  describe('deleteSegment', () => {
    it('Test 3: orphan handling — children get parentSegmentId=null', () => {
      const parentId = useSegmentStore.getState().addSegment(makeSegment({ name: 'Parent' }))
      const childId = useSegmentStore.getState().addSegment(makeSegment({ name: 'Child', parentSegmentId: parentId }))
      const grandchildId = useSegmentStore.getState().addSegment(makeSegment({ name: 'Grandchild', parentSegmentId: childId }))

      useSegmentStore.getState().deleteSegment(parentId)

      const state = useSegmentStore.getState()
      expect(state.segments[parentId]).toBeUndefined()
      expect(state.segments[childId].parentSegmentId).toBeNull()
      expect(state.segments[grandchildId].parentSegmentId).toBe(childId) // not affected
      expect(state.segmentOrder).not.toContain(parentId)
    })

    it('removes segment from segmentOrder', () => {
      const id = useSegmentStore.getState().addSegment(makeSegment())
      useSegmentStore.getState().deleteSegment(id)
      expect(useSegmentStore.getState().segmentOrder).not.toContain(id)
      expect(useSegmentStore.getState().segments[id]).toBeUndefined()
    })
  })

  describe('deleteByEquipmentId', () => {
    it('Test 4: cascade delete by equipmentId', () => {
      const equipId = 'eq-abc'
      const id1 = useSegmentStore.getState().addSegment(makeSegment({ equipmentId: equipId }))
      const id2 = useSegmentStore.getState().addSegment(makeSegment({ equipmentId: equipId }))
      const otherId = useSegmentStore.getState().addSegment(makeSegment({ equipmentId: 'eq-other' }))

      useSegmentStore.getState().deleteByEquipmentId(equipId)

      const state = useSegmentStore.getState()
      expect(state.segments[id1]).toBeUndefined()
      expect(state.segments[id2]).toBeUndefined()
      expect(state.segments[otherId]).toBeDefined()
    })

    it('orphans children of deleted equipment segments', () => {
      const equipId = 'eq-xyz'
      const parentId = useSegmentStore.getState().addSegment(makeSegment({ equipmentId: equipId }))
      const childId = useSegmentStore.getState().addSegment(makeSegment({ parentSegmentId: parentId }))

      useSegmentStore.getState().deleteByEquipmentId(equipId)

      expect(useSegmentStore.getState().segments[childId].parentSegmentId).toBeNull()
    })

    it('no-op when no segments match equipmentId', () => {
      useSegmentStore.getState().addSegment(makeSegment())
      const before = Object.keys(useSegmentStore.getState().segments).length
      useSegmentStore.getState().deleteByEquipmentId('nonexistent')
      expect(Object.keys(useSegmentStore.getState().segments).length).toBe(before)
    })
  })

  describe('deleteBySystemId', () => {
    it('removes all segments belonging to a system', () => {
      const id1 = useSegmentStore.getState().addSegment(makeSegment({ systemId: 'sys-del', name: 'A' }))
      const id2 = useSegmentStore.getState().addSegment(makeSegment({ systemId: 'sys-del', name: 'B' }))
      const otherId = useSegmentStore.getState().addSegment(makeSegment({ systemId: 'sys-keep', name: 'C' }))

      useSegmentStore.getState().deleteBySystemId('sys-del')

      const state = useSegmentStore.getState()
      expect(state.segments[id1]).toBeUndefined()
      expect(state.segments[id2]).toBeUndefined()
      expect(state.segments[otherId]).toBeDefined()
      expect(state.segmentOrder).not.toContain(id1)
      expect(state.segmentOrder).not.toContain(id2)
      expect(state.segmentOrder).toContain(otherId)
    })

    it('orphans cross-system children when parent is deleted', () => {
      const parentId = useSegmentStore.getState().addSegment(makeSegment({ systemId: 'sys-del' }))
      const childId = useSegmentStore.getState().addSegment(makeSegment({ systemId: 'sys-keep', parentSegmentId: parentId }))

      useSegmentStore.getState().deleteBySystemId('sys-del')

      expect(useSegmentStore.getState().segments[childId].parentSegmentId).toBeNull()
    })

    it('no-op when no segments match systemId', () => {
      useSegmentStore.getState().addSegment(makeSegment({ systemId: 'sys-1' }))
      const before = Object.keys(useSegmentStore.getState().segments).length
      useSegmentStore.getState().deleteBySystemId('nonexistent')
      expect(Object.keys(useSegmentStore.getState().segments).length).toBe(before)
    })
  })

  describe('bulkSetSystemId', () => {
    it('sets systemId on all segments', () => {
      useSegmentStore.getState().addSegment(makeSegment({ systemId: '' }))
      useSegmentStore.getState().addSegment(makeSegment({ systemId: '' }))
      useSegmentStore.getState().bulkSetSystemId('sys-migrated')
      const state = useSegmentStore.getState()
      for (const seg of Object.values(state.segments)) {
        expect(seg.systemId).toBe('sys-migrated')
      }
    })
  })

  describe('reorderSegments', () => {
    it('Test 5: changes segmentOrder', () => {
      const id1 = useSegmentStore.getState().addSegment(makeSegment({ name: 'A' }))
      const id2 = useSegmentStore.getState().addSegment(makeSegment({ name: 'B' }))
      const id3 = useSegmentStore.getState().addSegment(makeSegment({ name: 'C' }))

      useSegmentStore.getState().reorderSegments([id3, id1, id2])
      expect(useSegmentStore.getState().segmentOrder).toEqual([id3, id1, id2])
    })
  })

  describe('updateKmsCount', () => {
    it('Test 6: adds kms entry when count > 0', () => {
      const id = useSegmentStore.getState().addSegment(makeSegment())
      useSegmentStore.getState().updateKmsCount(id, 'elbow-90-smooth', 3)
      expect(useSegmentStore.getState().segments[id].kmsCounts['elbow-90-smooth']).toBe(3)
    })

    it('removes kms entry when count = 0', () => {
      const id = useSegmentStore.getState().addSegment(makeSegment({ kmsCounts: { 'valve-ball': 2 } }))
      useSegmentStore.getState().updateKmsCount(id, 'valve-ball', 0)
      expect(useSegmentStore.getState().segments[id].kmsCounts['valve-ball']).toBeUndefined()
    })

    it('preserves other kms entries on update', () => {
      const id = useSegmentStore.getState().addSegment(makeSegment({ kmsCounts: { 'elbow-90-smooth': 2, 'valve-ball': 1 } }))
      useSegmentStore.getState().updateKmsCount(id, 'elbow-90-smooth', 4)
      const counts = useSegmentStore.getState().segments[id].kmsCounts
      expect(counts['elbow-90-smooth']).toBe(4)
      expect(counts['valve-ball']).toBe(1)
    })
  })

  describe('clearAllSegments', () => {
    it('clears segments and segmentOrder', () => {
      useSegmentStore.getState().addSegment(makeSegment())
      useSegmentStore.getState().addSegment(makeSegment())
      useSegmentStore.getState().clearAllSegments()
      expect(Object.keys(useSegmentStore.getState().segments)).toHaveLength(0)
      expect(useSegmentStore.getState().segmentOrder).toHaveLength(0)
    })
  })

  describe('bulkAddSegments', () => {
    it('adds multiple segments and returns ids in order', () => {
      const segs = [
        makeSegment({ name: 'Bulk A' }),
        makeSegment({ name: 'Bulk B' }),
        makeSegment({ name: 'Bulk C' })
      ]
      const ids = useSegmentStore.getState().bulkAddSegments(segs)
      expect(ids).toHaveLength(3)
      const state = useSegmentStore.getState()
      expect(state.segments[ids[0]].name).toBe('Bulk A')
      expect(state.segments[ids[1]].name).toBe('Bulk B')
      expect(state.segments[ids[2]].name).toBe('Bulk C')
      expect(state.segmentOrder.slice(-3)).toEqual([...ids])
    })
  })

  describe('persist key isolation', () => {
    it('persist key is teplo-segments', () => {
      useSegmentStore.getState().addSegment(makeSegment())
      expect(localStorage.getItem('teplo-segments')).not.toBeNull()
    })
  })
})

describe('selectSegmentsByParent', () => {
  beforeEach(() => {
    useSegmentStore.setState({ segments: {}, segmentOrder: [] })
  })

  it('returns root segments (parentId=null) in order', () => {
    const id1 = useSegmentStore.getState().addSegment(makeSegment({ name: 'Root 1', parentSegmentId: null }))
    const id2 = useSegmentStore.getState().addSegment(makeSegment({ name: 'Root 2', parentSegmentId: null }))
    const childId = useSegmentStore.getState().addSegment(makeSegment({ name: 'Child', parentSegmentId: id1 }))

    const state = useSegmentStore.getState()
    const roots = selectSegmentsByParent(null)(state)
    expect(roots.map(s => s.id)).toEqual([id1, id2])
    expect(roots.find(s => s.id === childId)).toBeUndefined()
  })

  it('returns children of a given parent', () => {
    const parentId = useSegmentStore.getState().addSegment(makeSegment({ name: 'Parent' }))
    const c1 = useSegmentStore.getState().addSegment(makeSegment({ name: 'Child 1', parentSegmentId: parentId }))
    const c2 = useSegmentStore.getState().addSegment(makeSegment({ name: 'Child 2', parentSegmentId: parentId }))

    const state = useSegmentStore.getState()
    const children = selectSegmentsByParent(parentId)(state)
    expect(children.map(s => s.id)).toEqual([c1, c2])
  })
})
