/**
 * Segment store — normalized CRUD для участков гидравлики.
 * Pattern: Phase 2/3 (equipmentStore + enclosureStore orphan handling).
 * Persist key: 'teplo-segments'. Persists: segments + segmentOrder.
 *
 * Threat mitigation:
 *   T-04-08: IDs generated via uuid(), never accepted from external input.
 *   Input from UI (not raw JSON) — no prototype pollution path here.
 *
 * Decisions:
 *   D-03: segmentOrder defines display numbering order.
 *   D-02: equipmentId optional — null for magistral segments.
 *   D-09 (04.1): updateSegment returns boolean — false = cross-system parent reject.
 *   D-12 (04.1): systemId required on all segments.
 *   D-21 (04.1): autoGenerated reset to false on any user-facing edit.
 */

import { create } from 'zustand'
import { persist, createJSONStorage } from 'zustand/middleware'
import { toast } from 'sonner'
import { safeStorage, shapeMerge } from './safeStorage'
import { uuid } from './uuid'
import type { Segment, KmsCounts } from '../types/hydraulics'

/** Default velocities by segment kind (D-06). */
const VELOCITY_BY_KIND: Record<Segment['kind'], number> = {
  trunk: 0.8,
  riser: 0.5,
  branch: 0.4,
  connection: 0.3
}

export interface SegmentState {
  readonly segments: Record<string, Segment>
  readonly segmentOrder: readonly string[]
  addSegment: (seg: Omit<Segment, 'id'>) => string
  /** D-09: returns false if cross-system parent violation (UI shows toast on false). */
  updateSegment: (id: string, changes: Partial<Omit<Segment, 'id'>>) => boolean
  deleteSegment: (id: string) => void
  deleteByEquipmentId: (equipmentId: string) => void
  /** D-04.1 cascade: removes all segments belonging to a system. */
  deleteBySystemId: (systemId: string) => void
  /** D-25 migration: sets systemId on all segments (batch, programmatic). */
  bulkSetSystemId: (systemId: string) => void
  reorderSegments: (newOrder: readonly string[]) => void
  updateKmsCount: (segmentId: string, kmsId: string, count: number) => void
  clearAllSegments: () => void
  bulkAddSegments: (segs: ReadonlyArray<Omit<Segment, 'id'>>) => readonly string[]
}

export const defaultSegmentData = {
  segments: {} as Record<string, Segment>,
  segmentOrder: [] as string[]
}

export const useSegmentStore = create<SegmentState>()(
  persist(
    (set) => ({
      ...defaultSegmentData,

      addSegment: (seg: Omit<Segment, 'id'>): string => {
        const id = uuid()
        set(state => ({
          segments: { ...state.segments, [id]: { ...seg, id } as Segment },
          segmentOrder: [...state.segmentOrder, id]
        }))
        return id
      },

      updateSegment: (id: string, changes: Partial<Omit<Segment, 'id'>>): boolean => {
        let accepted = true
        set(state => {
          const current = state.segments[id]
          if (!current) { accepted = false; return state }

          // D-09: self-parent guard
          if (changes.parentSegmentId === id) { accepted = false; return state }

          // D-09: parentSegmentId must belong to the same system
          if (changes.parentSegmentId !== undefined && changes.parentSegmentId !== null) {
            const parent = state.segments[changes.parentSegmentId]
            const targetSystemId = changes.systemId ?? current.systemId
            if (parent && parent.systemId !== targetSystemId) {
              accepted = false
              // W3 revision (B3 path B): единый источник toast'а — store.
              // UI фильтрует опции dropdown'а same-system only, но race / programmatic path
              // сюда попасть всё же может, и пользователь получит внятный feedback.
              toast.error('Нельзя выбрать родителя из другой системы')
              return state  // reject cross-system parent
            }
          }

          // D-06 + D-21: if user changes kind and velocity matches old-kind default — update velocity
          const velocityOverride: Partial<Segment> =
            (changes.kind && changes.kind !== current.kind &&
              current.velocityTargetMS === VELOCITY_BY_KIND[current.kind])
              ? { velocityTargetMS: VELOCITY_BY_KIND[changes.kind] }
              : {}

          // D-21: reset autoGenerated on any user-facing edit (except programmatic systemId-only)
          const isProgrammatic = Object.keys(changes).length === 1 && 'systemId' in changes
          const autoGeneratedReset: Partial<Segment> =
            (!isProgrammatic && current.autoGenerated) ? { autoGenerated: false } : {}

          const patch: Partial<Segment> = { ...changes, ...velocityOverride, ...autoGeneratedReset }

          return {
            segments: {
              ...state.segments,
              [id]: { ...current, ...patch } as Segment
            }
          }
        })
        return accepted
      },

      deleteSegment: (id: string) => set(state => {
        const { [id]: _removed, ...rest } = state.segments
        // Orphan handling: children with parentSegmentId=id → parentSegmentId=null
        const segments: Record<string, Segment> = {}
        for (const [sid, seg] of Object.entries(rest)) {
          segments[sid] = seg.parentSegmentId === id
            ? { ...seg, parentSegmentId: null }
            : seg
        }
        return {
          segments,
          segmentOrder: state.segmentOrder.filter(sid => sid !== id)
        }
      }),

      deleteByEquipmentId: (equipmentId: string) => set(state => {
        const toRemove = new Set(
          Object.values(state.segments)
            .filter(s => s.equipmentId === equipmentId)
            .map(s => s.id)
        )
        if (toRemove.size === 0) return state
        const segments: Record<string, Segment> = {}
        for (const [sid, seg] of Object.entries(state.segments)) {
          if (toRemove.has(sid)) continue
          segments[sid] = toRemove.has(seg.parentSegmentId ?? '')
            ? { ...seg, parentSegmentId: null }
            : seg
        }
        return {
          segments,
          segmentOrder: state.segmentOrder.filter(sid => !toRemove.has(sid))
        }
      }),

      deleteBySystemId: (systemId: string) => set(state => {
        const toRemove = new Set(
          Object.values(state.segments).filter(s => s.systemId === systemId).map(s => s.id)
        )
        if (toRemove.size === 0) return state
        const segments: Record<string, Segment> = {}
        for (const [sid, seg] of Object.entries(state.segments)) {
          if (toRemove.has(sid)) continue
          segments[sid] = seg.parentSegmentId !== null && toRemove.has(seg.parentSegmentId)
            ? { ...seg, parentSegmentId: null }
            : seg
        }
        return {
          segments,
          segmentOrder: state.segmentOrder.filter(sid => !toRemove.has(sid))
        }
      }),

      bulkSetSystemId: (systemId: string) => set(state => {
        const segments: Record<string, Segment> = {}
        for (const [sid, seg] of Object.entries(state.segments)) {
          segments[sid] = { ...seg, systemId }
        }
        return { segments }
      }),

      reorderSegments: (newOrder: readonly string[]) => set({ segmentOrder: [...newOrder] }),

      updateKmsCount: (segmentId: string, kmsId: string, count: number) => set(state => {
        const seg = state.segments[segmentId]
        if (!seg) return state
        const newCounts: KmsCounts = count > 0
          ? { ...seg.kmsCounts, [kmsId]: count }
          : Object.fromEntries(Object.entries(seg.kmsCounts).filter(([k]) => k !== kmsId))
        return {
          segments: {
            ...state.segments,
            [segmentId]: { ...seg, kmsCounts: newCounts }
          }
        }
      }),

      clearAllSegments: () => set({ segments: {}, segmentOrder: [] }),

      bulkAddSegments: (segs: ReadonlyArray<Omit<Segment, 'id'>>): readonly string[] => {
        const newIds: string[] = []
        set(state => {
          const nextSegments = { ...state.segments }
          for (const s of segs) {
            const id = uuid()
            nextSegments[id] = { ...s, id } as Segment
            newIds.push(id)
          }
          return {
            segments: nextSegments,
            segmentOrder: [...state.segmentOrder, ...newIds]
          }
        })
        return newIds
      }
    }),
    {
      name: 'teplo-segments',
      version: 2,
      storage: createJSONStorage(() => safeStorage),
      migrate: (persistedState, version) => {
        if (version < 2) {
          // Fill placeholder fields for existing segments.
          // runV11Migration (App.tsx) will set correct systemId via bulkSetSystemId.
          const s = persistedState as { segments?: Record<string, Record<string, unknown>> } | null
          if (s?.segments) {
            for (const seg of Object.values(s.segments)) {
              if (seg.systemId === undefined) seg.systemId = ''
              if (seg.kind === undefined) seg.kind = 'branch'
              if (seg.autoGenerated === undefined) seg.autoGenerated = false
            }
          }
          return s
        }
        return persistedState
      },
      partialize: (state) => ({
        segments: state.segments,
        segmentOrder: state.segmentOrder
      } as unknown as SegmentState),
      // Phase 04.2: validate shape of persisted state, drop garbage to defaults.
      merge: (persisted, current) => shapeMerge(persisted, current as SegmentState, {
        segments: 'record',
        segmentOrder: 'array-of-string'
      }),
      onRehydrateStorage: () => (_state, error) => {
        if (error) {
          console.error('Segment rehydration failed:', error)
        }
      }
    }
  )
)

/** Selector — returns segments with given parentId in display order. */
export const selectSegmentsByParent = (parentId: string | null) =>
  (state: SegmentState): readonly Segment[] =>
    state.segmentOrder
      .map(id => state.segments[id])
      .filter((s): s is Segment => s !== undefined && s.parentSegmentId === parentId)
