/**
 * RED scaffold: per-system hydraulics — filterSegmentsBySystem, derivedQ.
 * Tests WILL FAIL until hydraulics.ts is extended in Plan 03.
 *
 * Covers:
 *   - filterSegmentsBySystem: per-system subset
 *   - derivedQ: Q-cascade, override, cycle guard, cross-system isolation
 *   - derivedQ MAX_DEPTH guard (B2 revision): terminates at depth > 20
 */

import { describe, it, expect } from 'vitest'
import { filterSegmentsBySystem, derivedQ, buildChildrenMap } from '../engine/hydraulics'
import type { Segment } from '../types/hydraulics'

// Helper: build minimal Segment stub
function makeSeg(id: string, systemId: string, overrides: Partial<Segment> = {}): Segment {
  return {
    id,
    systemId,
    parentSegmentId: null,
    name: id,
    equipmentId: null,
    qOverride: null,
    lengthM: 1,
    pipeId: 'steel-vgp-dn20',
    dnMm: null,
    kmsCounts: {},
    velocityTargetMS: 0.6,
    kind: 'trunk',
    autoGenerated: false,
    ...overrides
  } as unknown as Segment
}

describe('filterSegmentsBySystem', () => {
  it('returns only segments belonging to systemId', () => {
    const segments = {
      'seg-a1': makeSeg('seg-a1', 'sys-A'),
      'seg-a2': makeSeg('seg-a2', 'sys-A'),
      'seg-b1': makeSeg('seg-b1', 'sys-B')
    }
    const result = filterSegmentsBySystem(segments, 'sys-A')
    expect(Object.keys(result)).toHaveLength(2)
    expect(result['seg-a1']).toBeDefined()
    expect(result['seg-a2']).toBeDefined()
    expect(result['seg-b1']).toBeUndefined()
  })

  it('returns empty object for unknown systemId', () => {
    const segments = {
      'seg-a': makeSeg('seg-a', 'sys-A')
    }
    const result = filterSegmentsBySystem(segments, 'sys-UNKNOWN')
    expect(Object.keys(result)).toHaveLength(0)
  })

  it('preserves full Segment structure for each member', () => {
    const segments = {
      'seg-1': makeSeg('seg-1', 'sys-X', { lengthM: 5 })
    }
    const result = filterSegmentsBySystem(segments, 'sys-X')
    expect(result['seg-1'].lengthM).toBe(5)
  })
})

describe('derivedQ', () => {
  it('leaf with equipmentId returns equipmentQ[eid]', () => {
    const segments = {
      'seg-leaf': makeSeg('seg-leaf', 'sys-1', { equipmentId: 'eq-1' })
    }
    const childrenMap = buildChildrenMap(segments, 'sys-1')
    const q = derivedQ('seg-leaf', segments, { 'eq-1': 500 }, childrenMap)
    expect(q).toBe(500)
  })

  it('leaf with qOverride returns qOverride (wins over equipmentId)', () => {
    const segments = {
      'seg-leaf': makeSeg('seg-leaf', 'sys-1', { equipmentId: 'eq-1', qOverride: 300 })
    }
    const childrenMap = buildChildrenMap(segments, 'sys-1')
    const q = derivedQ('seg-leaf', segments, { 'eq-1': 500 }, childrenMap)
    expect(q).toBe(300)
  })

  it('parent with 2 children returns Σ children Q', () => {
    const segments = {
      'trunk': makeSeg('trunk', 'sys-1'),
      'child1': makeSeg('child1', 'sys-1', { parentSegmentId: 'trunk', equipmentId: 'eq-1' }),
      'child2': makeSeg('child2', 'sys-1', { parentSegmentId: 'trunk', equipmentId: 'eq-2' })
    }
    const childrenMap = buildChildrenMap(segments, 'sys-1')
    const q = derivedQ('trunk', segments, { 'eq-1': 300, 'eq-2': 200 }, childrenMap)
    expect(q).toBe(500)
  })

  it('3-level deep: trunk === Σ risers === Σ all connections', () => {
    const segments = {
      'trunk': makeSeg('trunk', 'sys-1', { kind: 'trunk' }),
      'riser1': makeSeg('riser1', 'sys-1', { parentSegmentId: 'trunk', kind: 'riser' }),
      'riser2': makeSeg('riser2', 'sys-1', { parentSegmentId: 'trunk', kind: 'riser' }),
      'conn1': makeSeg('conn1', 'sys-1', { parentSegmentId: 'riser1', equipmentId: 'eq-1', kind: 'connection' }),
      'conn2': makeSeg('conn2', 'sys-1', { parentSegmentId: 'riser1', equipmentId: 'eq-2', kind: 'connection' }),
      'conn3': makeSeg('conn3', 'sys-1', { parentSegmentId: 'riser2', equipmentId: 'eq-3', kind: 'connection' })
    }
    const eqQ = { 'eq-1': 100, 'eq-2': 150, 'eq-3': 200 }
    const childrenMap = buildChildrenMap(segments, 'sys-1')
    const trunkQ = derivedQ('trunk', segments, eqQ, childrenMap)
    const riser1Q = derivedQ('riser1', segments, eqQ, childrenMap)
    const riser2Q = derivedQ('riser2', segments, eqQ, childrenMap)
    expect(trunkQ).toBe(450) // 100+150+200
    expect(riser1Q).toBe(250) // 100+150
    expect(riser2Q).toBe(200)
  })

  it('cycle returns 0 (does not infinite loop)', () => {
    // A → B → A (self-cycle)
    const segments = {
      'seg-a': makeSeg('seg-a', 'sys-1', { parentSegmentId: 'seg-b' }),
      'seg-b': makeSeg('seg-b', 'sys-1', { parentSegmentId: 'seg-a' })
    }
    const childrenMap = buildChildrenMap(segments, 'sys-1')
    const q = derivedQ('seg-a', segments, {}, childrenMap)
    expect(q).toBe(0)
  })

  it('cross-system child is ignored (filter by same systemId)', () => {
    const segments = {
      'trunk': makeSeg('trunk', 'sys-1'),
      'child-same': makeSeg('child-same', 'sys-1', { parentSegmentId: 'trunk', equipmentId: 'eq-1' }),
      'child-other': makeSeg('child-other', 'sys-2', { parentSegmentId: 'trunk', equipmentId: 'eq-2' })
    }
    const childrenMap = buildChildrenMap(segments, 'sys-1')
    const q = derivedQ('trunk', segments, { 'eq-1': 300, 'eq-2': 500 }, childrenMap)
    // child-other belongs to sys-2 → excluded by buildChildrenMap
    expect(q).toBe(300)
  })
})

describe('derivedQ MAX_DEPTH guard (B2 revision)', () => {
  it('derivedQ terminates at MAX_DEPTH=20 on pathological chain (returns 0 beyond depth)', () => {
    // Build pathological linear chain of 25 segments (each is parent of the next).
    // Leaf (seg-24) has equipmentId with Q=100.
    // Expectation: derivedQ from root (seg-0) depth > 20 → returns 0 (truncates recursion).
    const systemId = 'sys-1'
    const segments: Record<string, Segment> = {}
    const equipmentQ: Record<string, number> = {}
    for (let i = 0; i < 25; i++) {
      const id = `seg-${i}`
      segments[id] = makeSeg(id, systemId, {
        parentSegmentId: i === 0 ? null : `seg-${i - 1}`,
        equipmentId: i === 24 ? 'eq-1' : null
      })
    }
    equipmentQ['eq-1'] = 100

    const childrenMap = buildChildrenMap(segments, systemId)
    // seg-0 is root: depth=0 → traverses to seg-24 at depth=24 > MAX_DEPTH=20 → truncated → returns 0
    const total = derivedQ('seg-0', segments, equipmentQ, childrenMap)
    expect(total).toBe(0)

    // Control: from seg-21 → seg-22 → seg-23 → seg-24 (eq-1) is within depth=3 from seg-21
    const sub = derivedQ('seg-21', segments, equipmentQ, childrenMap)
    expect(sub).toBe(100) // seg-21 → seg-22 → seg-23 → seg-24(eq-1) within MAX_DEPTH
  })
})
