/**
 * engine/skeleton.ts — D-20 3-level auto-skeleton generator.
 * Pure TS — zero React / store imports. Safe for Web Worker.
 * Pattern: 1 trunk + 1 riser-per-floor + 1 connection-per-equipment.
 */

import type { Segment } from '../types/hydraulics'
import type { Equipment, Room } from '../types/project'

/** D-06: default velocities per segment kind. */
export const VELOCITY_BY_KIND = {
  trunk: 0.8,
  riser: 0.5,
  branch: 0.4,
  connection: 0.3
} as const

export interface SkeletonInput {
  readonly systemId: string
  readonly rooms: Record<string, Room>
  readonly equipment: Record<string, Equipment>
  readonly equipmentOrder: readonly string[]
  /** Optional: default pipeId for generated segments (falls back to 'steel-vgp-dn20') */
  readonly defaultPipeId?: string
}

let _counter = 0
function skelId(prefix: string): string {
  return `skel-${prefix}-${++_counter}`
}

/**
 * D-20: generates a 3-level segment skeleton for a given system.
 * Returns flat array of Segment with IDs already set (autoGenerated: true).
 * Caller passes result to bulkAddSegments / store.
 *
 * Hierarchy: trunk → riser (per floor) → connection (per equipment on that floor).
 */
export function generateSkeleton(input: SkeletonInput): readonly Segment[] {
  const { systemId, rooms, equipment, equipmentOrder, defaultPipeId = 'steel-vgp-dn20' } = input

  const result: Segment[] = []

  // Create trunk
  const trunkId = skelId('trunk')
  const trunk: Segment = {
    id: trunkId,
    systemId,
    parentSegmentId: null,
    name: 'Магистраль',
    kind: 'trunk',
    equipmentId: null,
    qOverride: null,
    lengthM: 1,
    pipeId: defaultPipeId,
    dnMm: null,
    kmsCounts: {},
    velocityTargetMS: VELOCITY_BY_KIND.trunk,
    autoGenerated: true
  }
  result.push(trunk)

  if (equipmentOrder.length === 0) {
    return result
  }

  // Group equipment by floor (via rooms lookup)
  const byFloor = new Map<number, string[]>()  // floor → equipmentIds
  for (const eqId of equipmentOrder) {
    const eq = equipment[eqId]
    if (!eq) continue
    // Filter to this system only
    if (eq.systemId !== systemId) continue
    const room = rooms[eq.roomId]
    const floor = room?.floor ?? 1
    if (!byFloor.has(floor)) byFloor.set(floor, [])
    byFloor.get(floor)!.push(eqId)
  }

  if (byFloor.size === 0) {
    return result
  }

  const floors = [...byFloor.keys()].sort((a, b) => a - b)

  for (const floor of floors) {
    const eqIds = byFloor.get(floor)!

    // Create riser for this floor
    const riserId = skelId(`riser-f${floor}`)
    const riser: Segment = {
      id: riserId,
      systemId,
      parentSegmentId: trunkId,
      name: `Стояк этаж ${floor}`,
      kind: 'riser',
      equipmentId: null,
      qOverride: null,
      lengthM: 1,
      pipeId: defaultPipeId,
      dnMm: null,
      kmsCounts: {},
      velocityTargetMS: VELOCITY_BY_KIND.riser,
      autoGenerated: true
    }
    result.push(riser)

    // Create connection for each equipment on this floor
    for (const eqId of eqIds) {
      const eq = equipment[eqId]
      const connId = skelId(`conn-${eqId}`)
      const conn: Segment = {
        id: connId,
        systemId,
        parentSegmentId: riserId,
        name: `Подводка ${eq?.id ?? eqId}`,
        kind: 'connection',
        equipmentId: eqId,
        qOverride: null,
        lengthM: 1,
        pipeId: defaultPipeId,
        dnMm: null,
        kmsCounts: {},
        velocityTargetMS: VELOCITY_BY_KIND.connection,
        autoGenerated: true
      }
      result.push(conn)
    }
  }

  return result
}
