/**
 * RED scaffold: generateSkeleton pure function.
 * Tests WILL FAIL until engine/skeleton.ts is implemented in Plan 02.
 *
 * Covers:
 *   - empty equipment → single trunk
 *   - 2 floors → 1 trunk + 2 risers + N connections
 *   - connections have equipmentId populated
 *   - connections parentSegmentId refers to correct floor's riser
 *   - VELOCITY_BY_KIND constants
 *   - autoGenerated: true on all generated segments
 */

import { describe, it, expect } from 'vitest'
import { generateSkeleton, VELOCITY_BY_KIND } from '../engine/skeleton'
import type { Segment } from '../types/hydraulics'
import type { Equipment } from '../types/project'
import type { Room } from '../types/project'

// Helper types
interface SkeletonInput {
  systemId: string
  rooms: Record<string, Room>
  equipment: Record<string, Equipment>
  equipmentOrder: readonly string[]
}

const makeRoom = (id: string, floor: number): Room => ({
  id,
  number: 1,
  name: `Room ${id}`,
  floor,
  area: 20,
  height: 2.7,
  isCorner: false,
  infiltrationMethod: 'rate' as const,
  nInfiltration: null,
  gapArea: null,
  windSpeed: null,
  lVentilation: 0,
  tInside: 20
})

const makeEquipment = (id: string, roomId: string, systemId: string): Equipment => ({
  id,
  roomId,
  kind: 'bimetal' as const,
  catalogModelId: null,
  connection: 'side' as const,
  installation: 'open' as const,
  panelType: null,
  panelHeightMm: null,
  panelLengthMm: null,
  sectionsOverride: null,
  convectorLengthMm: null,
  manualQNominal: null,
  manualNExponent: null,
  systemId
} as unknown as Equipment)

describe('generateSkeleton', () => {
  it('empty equipment → returns single trunk segment only', () => {
    const input: SkeletonInput = {
      systemId: 'sys-1',
      rooms: { 'room-1': makeRoom('room-1', 1) },
      equipment: {},
      equipmentOrder: []
    }
    const segments = generateSkeleton(input)
    expect(segments).toHaveLength(1)
    expect(segments[0].kind).toBe('trunk')
    expect(segments[0].parentSegmentId).toBeNull()
    expect(segments[0].autoGenerated).toBe(true)
  })

  it('equipment on 2 floors → 1 trunk + 2 risers + N connections', () => {
    const rooms = {
      'room-1': makeRoom('room-1', 1),
      'room-2': makeRoom('room-2', 1),
      'room-3': makeRoom('room-3', 2)
    }
    const equipment = {
      'eq-1': makeEquipment('eq-1', 'room-1', 'sys-1'),
      'eq-2': makeEquipment('eq-2', 'room-2', 'sys-1'),
      'eq-3': makeEquipment('eq-3', 'room-3', 'sys-1')
    }
    const input: SkeletonInput = {
      systemId: 'sys-1',
      rooms,
      equipment,
      equipmentOrder: ['eq-1', 'eq-2', 'eq-3']
    }
    const segments = generateSkeleton(input)
    const trunks = segments.filter(s => s.kind === 'trunk')
    const risers = segments.filter(s => s.kind === 'riser')
    const connections = segments.filter(s => s.kind === 'connection')

    expect(trunks).toHaveLength(1)
    expect(risers).toHaveLength(2) // floor 1 + floor 2
    expect(connections).toHaveLength(3) // one per equipment
    expect(segments).toHaveLength(1 + 2 + 3)
  })

  it('connections have equipmentId populated', () => {
    const rooms = { 'room-1': makeRoom('room-1', 1) }
    const equipment = { 'eq-1': makeEquipment('eq-1', 'room-1', 'sys-1') }
    const input: SkeletonInput = {
      systemId: 'sys-1',
      rooms,
      equipment,
      equipmentOrder: ['eq-1']
    }
    const segments = generateSkeleton(input)
    const connections = segments.filter(s => s.kind === 'connection')
    expect(connections).toHaveLength(1)
    expect(connections[0].equipmentId).toBe('eq-1')
  })

  it('connections parentSegmentId refers to riser of correct floor', () => {
    const rooms = {
      'room-f1': makeRoom('room-f1', 1),
      'room-f2': makeRoom('room-f2', 2)
    }
    const equipment = {
      'eq-f1': makeEquipment('eq-f1', 'room-f1', 'sys-1'),
      'eq-f2': makeEquipment('eq-f2', 'room-f2', 'sys-1')
    }
    const input: SkeletonInput = {
      systemId: 'sys-1',
      rooms,
      equipment,
      equipmentOrder: ['eq-f1', 'eq-f2']
    }
    const segments = generateSkeleton(input)
    const risers = segments.filter(s => s.kind === 'riser')
    const connections = segments.filter(s => s.kind === 'connection')

    // Each connection's parent should be a riser
    for (const conn of connections) {
      expect(conn.parentSegmentId).not.toBeNull()
      const parentRiser = risers.find(r => r.id === conn.parentSegmentId)
      expect(parentRiser).toBeDefined()
    }

    // Connection for equipment on floor 1 must have a different parent than floor 2 equipment
    const connF1 = connections.find(c => c.equipmentId === 'eq-f1')
    const connF2 = connections.find(c => c.equipmentId === 'eq-f2')
    expect(connF1?.parentSegmentId).not.toBe(connF2?.parentSegmentId)
  })

  it('all generated segments have autoGenerated: true', () => {
    const rooms = { 'room-1': makeRoom('room-1', 1) }
    const equipment = { 'eq-1': makeEquipment('eq-1', 'room-1', 'sys-1') }
    const input: SkeletonInput = {
      systemId: 'sys-1',
      rooms,
      equipment,
      equipmentOrder: ['eq-1']
    }
    const segments = generateSkeleton(input)
    for (const seg of segments) {
      expect(seg.autoGenerated).toBe(true)
    }
  })

  it('all generated segments have systemId = input systemId', () => {
    const rooms = { 'room-1': makeRoom('room-1', 1) }
    const input: SkeletonInput = {
      systemId: 'sys-X',
      rooms,
      equipment: {},
      equipmentOrder: []
    }
    const segments = generateSkeleton(input)
    for (const seg of segments) {
      expect((seg as unknown as Record<string, unknown>).systemId).toBe('sys-X')
    }
  })
})

describe('VELOCITY_BY_KIND constants', () => {
  it('exports VELOCITY_BY_KIND with expected values', () => {
    expect(VELOCITY_BY_KIND).toBeDefined()
    expect(VELOCITY_BY_KIND.trunk).toBe(0.8)
    expect(VELOCITY_BY_KIND.riser).toBe(0.5)
    expect(VELOCITY_BY_KIND.branch).toBe(0.4)
    expect(VELOCITY_BY_KIND.connection).toBe(0.3)
  })
})
