/**
 * RED scaffold: buildSegmentTree pure DFS builder.
 * Tests WILL FAIL until engine/tree.ts is implemented in Plan 04.
 *
 * Covers:
 *   - empty/unknown systemId
 *   - flat list → depth 0
 *   - 3-level hierarchy → pre-order [trunk, riser, connection]
 *   - cycle guard (visited set)
 *   - MAX_DEPTH = 20 cutoff
 *   - cross-system filtering
 */

import { describe, it, expect } from 'vitest'
import { buildSegmentTree } from '../engine/tree'
import type { Segment } from '../types/hydraulics'
import type { SegmentTreeNode } from '../hooks/useSegmentTree'

// Helper: build minimal Segment stub
function makeSeg(id: string, systemId: string, overrides: Partial<Segment> = {}): Segment {
  return {
    id,
    systemId,
    parentSegmentId: null,
    name: id,
    equipmentId: null,
    qOverride: null,
    lengthM: 1,
    pipeId: 'steel-vgp-dn20',
    dnMm: null,
    kmsCounts: {},
    velocityTargetMS: 0.6,
    kind: 'trunk',
    autoGenerated: false,
    ...overrides
  } as unknown as Segment
}

describe('buildSegmentTree', () => {
  it('returns empty array for unknown systemId', () => {
    const segments = {
      'seg-1': makeSeg('seg-1', 'sys-A')
    }
    const result = buildSegmentTree(segments, ['seg-1'], 'sys-UNKNOWN')
    expect(result).toHaveLength(0)
  })

  it('flat list of trunks → all at depth 0', () => {
    const segments = {
      'trunk-1': makeSeg('trunk-1', 'sys-1'),
      'trunk-2': makeSeg('trunk-2', 'sys-1')
    }
    const result = buildSegmentTree(segments, ['trunk-1', 'trunk-2'], 'sys-1')
    expect(result).toHaveLength(2)
    expect(result[0].depth).toBe(0)
    expect(result[1].depth).toBe(0)
  })

  it('trunk → riser → connection: pre-order DFS [trunk(d=0), riser(d=1), connection(d=2)]', () => {
    const segments = {
      'trunk': makeSeg('trunk', 'sys-1'),
      'riser': makeSeg('riser', 'sys-1', { parentSegmentId: 'trunk', kind: 'riser' }),
      'conn': makeSeg('conn', 'sys-1', { parentSegmentId: 'riser', kind: 'connection' })
    }
    const result = buildSegmentTree(segments, ['trunk', 'riser', 'conn'], 'sys-1')
    expect(result).toHaveLength(3)
    expect(result[0].id).toBe('trunk')
    expect(result[0].depth).toBe(0)
    expect(result[1].id).toBe('riser')
    expect(result[1].depth).toBe(1)
    expect(result[2].id).toBe('conn')
    expect(result[2].depth).toBe(2)
  })

  it('pre-order: children appear after parent, before parent siblings', () => {
    const segments = {
      'trunk1': makeSeg('trunk1', 'sys-1'),
      'trunk2': makeSeg('trunk2', 'sys-1'),
      'riser1': makeSeg('riser1', 'sys-1', { parentSegmentId: 'trunk1', kind: 'riser' })
    }
    const result = buildSegmentTree(segments, ['trunk1', 'trunk2', 'riser1'], 'sys-1')
    // Pre-order: trunk1 → riser1 → trunk2
    const ids = result.map(n => n.id)
    expect(ids.indexOf('trunk1')).toBeLessThan(ids.indexOf('riser1'))
    expect(ids.indexOf('riser1')).toBeLessThan(ids.indexOf('trunk2'))
  })

  describe('cycle guard', () => {
    it('self-parent terminates gracefully', () => {
      const segments = {
        'seg-self': makeSeg('seg-self', 'sys-1', { parentSegmentId: 'seg-self' })
      }
      // Should not throw or loop infinitely
      const result = buildSegmentTree(segments, ['seg-self'], 'sys-1')
      expect(Array.isArray(result)).toBe(true)
    })

    it('A → B → A mutual cycle terminates gracefully', () => {
      const segments = {
        'seg-a': makeSeg('seg-a', 'sys-1', { parentSegmentId: 'seg-b' }),
        'seg-b': makeSeg('seg-b', 'sys-1', { parentSegmentId: 'seg-a' })
      }
      const result = buildSegmentTree(segments, ['seg-a', 'seg-b'], 'sys-1')
      expect(Array.isArray(result)).toBe(true)
      // Must terminate without infinite recursion
    })
  })

  it('MAX_DEPTH = 20: depth > 20 is cut off', () => {
    const systemId = 'sys-1'
    const segments: Record<string, Segment> = {}
    const order: string[] = []
    // Build chain of 25 segments (0→1→2→...→24)
    for (let i = 0; i < 25; i++) {
      const id = `seg-${i}`
      segments[id] = makeSeg(id, systemId, {
        parentSegmentId: i === 0 ? null : `seg-${i - 1}`
      })
      order.push(id)
    }
    const result = buildSegmentTree(segments, order, systemId)
    // MAX_DEPTH=20: nodes at depth > 20 should not appear
    const maxDepth = Math.max(...result.map((n: SegmentTreeNode) => n.depth))
    expect(maxDepth).toBeLessThanOrEqual(20)
    // Nodes at depth > 20 should be absent
    const deepNodes = result.filter((n: SegmentTreeNode) => n.depth > 20)
    expect(deepNodes).toHaveLength(0)
  })

  it('cross-system filtering: segments of other system not in tree', () => {
    const segments = {
      'seg-a': makeSeg('seg-a', 'sys-A'),
      'seg-b': makeSeg('seg-b', 'sys-B'),
      'seg-a-child': makeSeg('seg-a-child', 'sys-A', { parentSegmentId: 'seg-a', kind: 'riser' })
    }
    const result = buildSegmentTree(segments, ['seg-a', 'seg-b', 'seg-a-child'], 'sys-A')
    const ids = result.map((n: SegmentTreeNode) => n.id)
    expect(ids).not.toContain('seg-b')
    expect(ids).toContain('seg-a')
    expect(ids).toContain('seg-a-child')
  })
})
