/**
 * AddSegmentDialog — модалка ручного добавления сегмента в систему.
 * Заменяет неявный путь через "Регенерировать скелет": инженер явно выбирает
 * kind + parent + имя, получает новый сегмент с autoGenerated=false.
 */

import { useEffect, useMemo, useRef, useState } from 'react'
import { useShallow } from 'zustand/react/shallow'
import { toast } from 'sonner'
import { Button } from '../ui/Button'
import { useSegmentStore } from '../../store/segmentStore'
import { VELOCITY_BY_KIND } from '../../engine/skeleton'
import type { Segment } from '../../types/hydraulics'

const KIND_LABELS: Record<Segment['kind'], string> = {
  trunk: 'Магистраль',
  riser: 'Стояк',
  branch: 'Ответвление',
  connection: 'Подводка'
}

interface AddSegmentDialogProps {
  readonly open: boolean
  readonly systemId: string
  readonly defaultPipeId: string
  readonly onClose: () => void
}

export function AddSegmentDialog({ open, systemId, defaultPipeId, onClose }: AddSegmentDialogProps) {
  const segments = useSegmentStore(useShallow(s => s.segments))
  const addSegment = useSegmentStore(s => s.addSegment)

  const [kind, setKind] = useState<Segment['kind']>('branch')
  const [parentId, setParentId] = useState<string>('')
  const [name, setName] = useState<string>('')
  const nameInputRef = useRef<HTMLInputElement>(null)

  // Parent options: все сегменты этой системы.
  const parentOptions = useMemo(
    () => Object.values(segments).filter(s => s.systemId === systemId),
    [segments, systemId]
  )

  // Smart default name при смене kind.
  useEffect(() => {
    if (!open) return
    const sameKindCount = parentOptions.filter(s => s.kind === kind).length
    setName(`${KIND_LABELS[kind]} ${sameKindCount + 1}`)
  }, [kind, open, parentOptions])

  // Auto-set parent: первый trunk/riser в системе если ещё не выбран.
  useEffect(() => {
    if (!open) return
    if (parentId !== '' && parentOptions.some(s => s.id === parentId)) return
    if (kind === 'trunk') {
      setParentId('')
      return
    }
    const preferredParent =
      kind === 'riser'
        ? parentOptions.find(s => s.kind === 'trunk')
        : kind === 'branch'
          ? parentOptions.find(s => s.kind === 'riser') ?? parentOptions.find(s => s.kind === 'trunk')
          : parentOptions.find(s => s.kind === 'riser') ?? parentOptions.find(s => s.kind === 'branch')
    setParentId(preferredParent?.id ?? '')
  }, [kind, open, parentOptions, parentId])

  // Focus name input when opened.
  useEffect(() => {
    if (open) {
      setTimeout(() => nameInputRef.current?.focus(), 50)
    }
  }, [open])

  // Escape closes.
  useEffect(() => {
    if (!open) return
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  }, [open, onClose])

  if (!open) return null

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    const trimmedName = name.trim() || KIND_LABELS[kind]
    addSegment({
      systemId,
      parentSegmentId: parentId === '' ? null : parentId,
      name: trimmedName,
      equipmentId: null,
      qOverride: null,
      lengthM: 1,
      pipeId: defaultPipeId,
      dnMm: null,
      kmsCounts: {},
      velocityTargetMS: VELOCITY_BY_KIND[kind],
      kind,
      autoGenerated: false
    })
    toast.success(`Сегмент «${trimmedName}» добавлен`)
    onClose()
  }

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="add-segment-title"
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/40"
      onClick={e => e.target === e.currentTarget && onClose()}
    >
      <form
        onSubmit={handleSubmit}
        className="bg-[var(--color-bg)] border border-[var(--color-border)] rounded-md p-5 w-full max-w-md mx-4 shadow-lg flex flex-col gap-3"
      >
        <h3 id="add-segment-title" className="text-base font-semibold">
          Добавить сегмент
        </h3>

        <label className="flex flex-col gap-1">
          <span className="text-xs text-[var(--color-text-secondary)]">Тип участка</span>
          <select
            value={kind}
            onChange={e => setKind(e.target.value as Segment['kind'])}
            className="border border-[var(--color-border)] rounded px-2 py-1 text-sm bg-[var(--color-bg)] text-[var(--color-text-primary)]"
          >
            <option value="trunk">Магистраль — подача от источника</option>
            <option value="riser">Стояк — вертикальный участок между этажами</option>
            <option value="branch">Ответвление — горизонтальная ветка на этаже</option>
            <option value="connection">Подводка — участок к прибору</option>
          </select>
        </label>

        <label className="flex flex-col gap-1">
          <span className="text-xs text-[var(--color-text-secondary)]">Родитель</span>
          <select
            value={parentId}
            onChange={e => setParentId(e.target.value)}
            className="border border-[var(--color-border)] rounded px-2 py-1 text-sm bg-[var(--color-bg)] text-[var(--color-text-primary)]"
          >
            <option value="">— (нет, корневой сегмент)</option>
            {parentOptions.map(p => (
              <option key={p.id} value={p.id}>
                {p.name} · {KIND_LABELS[p.kind]}
              </option>
            ))}
          </select>
          <span className="text-xs text-[var(--color-text-secondary)] mt-0.5">
            Родитель — только сегменты этой системы
          </span>
        </label>

        <label className="flex flex-col gap-1">
          <span className="text-xs text-[var(--color-text-secondary)]">Имя сегмента</span>
          <input
            ref={nameInputRef}
            type="text"
            value={name}
            onChange={e => setName(e.target.value)}
            maxLength={60}
            className="border border-[var(--color-border)] rounded px-2 py-1 text-sm bg-[var(--color-bg)] text-[var(--color-text-primary)]"
          />
        </label>

        <div className="flex justify-end gap-2 mt-2">
          <Button type="button" variant="secondary" size="sm" onClick={onClose}>
            Отмена
          </Button>
          <Button type="submit" variant="primary" size="sm">
            Создать
          </Button>
        </div>
      </form>
    </div>
  )
}
