/**
 * RED scaffold: SegmentTable tree rendering tests (D-18, D-19).
 * Tests WILL FAIL until SegmentTable is extended with tree support in Plan 05.
 *
 * Covers:
 *   - tree rendering: pre-order DFS, indent, kind icon, chevron only on parents
 *   - chevron collapse hides children from DOM (not just display:none)
 *   - per-system numbering (D-19): independent № per system
 *   - ГЦК highlight per-system
 *   - cross-system: segment of other system not in table
 *   - W3 revision (D-09): cross-system parent toast error
 */

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { act, fireEvent, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import '@testing-library/jest-dom/vitest'
import { toast } from 'sonner'
import { SegmentTable } from './SegmentTable'
import { useSegmentStore } from '../../store/segmentStore'
import { useSystemStore } from '../../store/systemStore'
import type { Segment } from '../../types/hydraulics'

vi.mock('sonner', () => ({
  toast: {
    success: vi.fn(),
    error: vi.fn(),
    warning: vi.fn(),
    info: vi.fn()
  }
}))

beforeEach(() => {
  act(() => {
    useSegmentStore.setState({ segments: {}, segmentOrder: [] })
    useSystemStore.setState({ systems: {}, systemOrder: [] })
  })
})

afterEach(() => {
  vi.restoreAllMocks()
})

function addSystem(name: string): string {
  let id = ''
  act(() => {
    id = useSystemStore.getState().addSystem({
      name,
      schemaType: 'two-pipe-dead-end',
      pipeMaterialId: 'steel-vgp-dn20',
      coolantId: 'water',
      tSupply: 80,
      tReturn: 60,
      tSupplyUfh: 45,
      tReturnUfh: 35,
      sourceLabel: ''
    })
  })
  return id
}

function addSeg(systemId: string, overrides: Partial<Segment> = {}): string {
  let id = ''
  act(() => {
    id = useSegmentStore.getState().addSegment({
      systemId,
      parentSegmentId: null,
      name: 'Сегмент',
      equipmentId: null,
      qOverride: null,
      lengthM: 5,
      pipeId: 'steel-vgp-dn20',
      dnMm: null,
      kmsCounts: {},
      velocityTargetMS: 0.6,
      kind: 'trunk',
      autoGenerated: false,
      ...overrides
    } as unknown as Omit<Segment, 'id'>)
  })
  return id
}

describe('tree rendering', () => {
  it('renders pre-order DFS order: trunk, riser, connection', () => {
    const sysId = addSystem('Система 1')
    const trunkId = addSeg(sysId, { name: 'Магистраль', kind: 'trunk' } as Partial<Segment>)
    const riserId = addSeg(sysId, { name: 'Стояк', kind: 'riser', parentSegmentId: trunkId } as Partial<Segment>)
    const connId = addSeg(sysId, { name: 'Подводка', kind: 'connection', parentSegmentId: riserId } as Partial<Segment>)
    render(<SegmentTable systemId={sysId} />)
    const rows = screen.getAllByRole('row')
    const names = rows.map(r => r.textContent ?? '')
    const trunkIdx = names.findIndex(t => t.includes('Магистраль'))
    const riserIdx = names.findIndex(t => t.includes('Стояк'))
    const connIdx = names.findIndex(t => t.includes('Подводка'))
    expect(trunkIdx).toBeLessThan(riserIdx)
    expect(riserIdx).toBeLessThan(connIdx)
  })

  it('indent increases with depth (paddingLeft or data-depth attribute)', () => {
    const sysId = addSystem('Система 1')
    const trunkId = addSeg(sysId, { name: 'Магистраль', kind: 'trunk' } as Partial<Segment>)
    addSeg(sysId, { name: 'Стояк', kind: 'riser', parentSegmentId: trunkId } as Partial<Segment>)
    const { container } = render(<SegmentTable systemId={sysId} />)
    // Verify that rows have some depth indicator (style or data attribute)
    const depthIndicators = container.querySelectorAll('[data-depth], [style*="padding"]')
    expect(depthIndicators.length).toBeGreaterThan(0)
  })

  it('kind icon rendered before name (aria-hidden svg or icon element)', () => {
    const sysId = addSystem('Система 1')
    addSeg(sysId, { name: 'Магистраль', kind: 'trunk' } as Partial<Segment>)
    const { container } = render(<SegmentTable systemId={sysId} />)
    // Icon should be aria-hidden
    const icons = container.querySelectorAll('[aria-hidden="true"] svg, svg[aria-hidden="true"]')
    expect(icons.length).toBeGreaterThan(0)
  })

  it('chevron only appears on parent nodes (not leaf connection)', () => {
    const sysId = addSystem('Система 1')
    const trunkId = addSeg(sysId, { name: 'Магистраль', kind: 'trunk' } as Partial<Segment>)
    const riserId = addSeg(sysId, { name: 'Стояк', kind: 'riser', parentSegmentId: trunkId } as Partial<Segment>)
    const connId = addSeg(sysId, { name: 'Подводка', kind: 'connection', parentSegmentId: riserId } as Partial<Segment>)
    render(<SegmentTable systemId={sysId} />)
    // Connection (leaf) should not have a chevron toggle button
    // Parent rows should have chevron buttons
    const chevronButtons = screen.queryAllByRole('button', { name: /expand|collapse|развернуть|свернуть/i })
    // Trunk and riser have children → should have chevrons
    expect(chevronButtons.length).toBeGreaterThanOrEqual(2)
  })

  it('collapsed chevron hides children from DOM (not just display:none)', async () => {
    const user = userEvent.setup()
    const sysId = addSystem('Система 1')
    const trunkId = addSeg(sysId, { name: 'Магистраль', kind: 'trunk' } as Partial<Segment>)
    addSeg(sysId, { name: 'Стояк', kind: 'riser', parentSegmentId: trunkId } as Partial<Segment>)
    render(<SegmentTable systemId={sysId} />)
    // Initially expanded: riser is visible
    expect(screen.getByText('Стояк')).toBeInTheDocument()
    // Collapse trunk
    const chevron = screen.getByRole('button', { name: /expand|collapse|развернуть|свернуть/i })
    await user.click(chevron)
    // After collapse: riser should NOT be in document (not just hidden)
    expect(screen.queryByText('Стояк')).not.toBeInTheDocument()
  })
})

describe('per-system numbering (D-19)', () => {
  it('System A with 3 segments → № 1, 2, 3; System B with 2 → № 1, 2 (independent)', () => {
    const sysA = addSystem('Система A')
    const sysB = addSystem('Система B')
    addSeg(sysA, { name: 'Сег A1' } as Partial<Segment>)
    addSeg(sysA, { name: 'Сег A2' } as Partial<Segment>)
    addSeg(sysA, { name: 'Сег A3' } as Partial<Segment>)
    addSeg(sysB, { name: 'Сег B1' } as Partial<Segment>)
    addSeg(sysB, { name: 'Сег B2' } as Partial<Segment>)

    const { unmount } = render(<SegmentTable systemId={sysA} />)
    // System A should have rows numbered 1, 2, 3
    expect(screen.getByText('1')).toBeInTheDocument()
    expect(screen.getByText('2')).toBeInTheDocument()
    expect(screen.getByText('3')).toBeInTheDocument()
    unmount()

    render(<SegmentTable systemId={sysB} />)
    // System B should also start from 1 (independent numbering)
    const cells = screen.getAllByText('1')
    expect(cells.length).toBeGreaterThanOrEqual(1)
  })
})

describe('ГЦК highlight per-system', () => {
  it('segment with isInMainCircuit=true receives highlight class/style', () => {
    const sysId = addSystem('Система 1')
    addSeg(sysId, { name: 'Магистраль', kind: 'trunk', isInMainCircuit: true } as Partial<Segment>)
    const { container } = render(<SegmentTable systemId={sysId} />)
    // Row should have some highlight marker
    const highlighted = container.querySelectorAll('[data-gck="true"], .gck-highlight, [class*="main-circuit"], [class*="highlight"]')
    expect(highlighted.length).toBeGreaterThan(0)
  })
})

describe('cross-system filtering', () => {
  it('segment of other system does not appear in table (filter by systemId prop)', () => {
    const sysA = addSystem('Система A')
    const sysB = addSystem('Система B')
    addSeg(sysA, { name: 'Сегмент A' } as Partial<Segment>)
    addSeg(sysB, { name: 'Сегмент B' } as Partial<Segment>)
    render(<SegmentTable systemId={sysA} />)
    expect(screen.getByText('Сегмент A')).toBeInTheDocument()
    expect(screen.queryByText('Сегмент B')).not.toBeInTheDocument()
  })
})

describe('cross-system parent toast (W3 revision, D-09)', () => {
  it('shows toast error when user tries to set cross-system parent via updateSegment', async () => {
    const toastSpy = vi.spyOn(toast, 'error').mockImplementation(() => 'mock-id' as unknown as ReturnType<typeof toast.error>)
    const sysA = addSystem('Система A')
    const sysB = addSystem('Система B')
    const segA = addSeg(sysA, { name: 'Сег A' } as Partial<Segment>)
    const segB = addSeg(sysB, { name: 'Сег B' } as Partial<Segment>)

    // Attempt to set cross-system parent via updateSegment
    act(() => {
      // updateSegment should detect cross-system parent and reject
      useSegmentStore.getState().updateSegment(segA, { parentSegmentId: segB } as Partial<Omit<Segment, 'id'>>)
    })

    expect(toastSpy).toHaveBeenCalledWith(
      expect.stringContaining('Нельзя выбрать родителя из другой системы')
    )
    toastSpy.mockRestore()
  })
})
