/**
 * SegmentRow — accordion строка участка гидравлики (Phase 04.1).
 * Compact: indent + chevron (опц.) + kind icon + назначение + Q/L/d_пр/v/ΔP + delete.
 * Expanded: kind selector, parent selector (filter same-system + helper + toast on reject),
 *           TopologyWarnings, SegmentDetails (KMS), autoGenerated badge.
 * ГЦК подсветка через var(--gck-bg) + border-l-4 border-l-[var(--gck-strip)].
 *
 * Decisions:
 *   D-02: Q — readonly если equipmentId заполнен (auto), иначе editable.
 *   D-06: kind определяет дефолтную velocity (store applies на смене).
 *   D-09: store блокирует cross-system parent; toast — источник в store.
 *   D-11: ГЦК highlight через CSS tokens.
 *   D-18: depth-based paddingLeft, chevron только на parent-узлах.
 *   D-21: autoGenerated reset в store при ручном изменении.
 */

import { useMemo, useState } from 'react'
import { ChevronRight } from 'lucide-react'
import { useShallow } from 'zustand/react/shallow'
import { useSegmentStore } from '../../store/segmentStore'
import { useEquipmentStore } from '../../store/equipmentStore'
import { useProjectStore } from '../../store/projectStore'
import { useCatalogStore } from '../../store/catalogStore'
import { SegmentDetails } from './SegmentDetails'
import { KmsPicker } from './KmsPicker'
import { SegmentKindIcon } from './SegmentKindIcon'
import { TopologyWarnings } from './TopologyWarnings'
import { ConfirmDialog } from '../ui/ConfirmDialog'
import { INPUT_CLASS, formatDeltaP, formatVelocity, formatDiameter } from './hydraulics-help'
import { buildEquipmentModelName } from './equipment-label'
import type { Segment } from '../../types/hydraulics'
import type { SegmentCalcResult } from '../../engine/hydraulics'

// Легаси-паттерны автогенерированных имён (до Вариант-1 очистки).
const LEGACY_NAME_PATTERN = /^(Участок|К прибору)\s+[a-z0-9]{4}$/i

const KIND_LABELS: Record<Segment['kind'], string> = {
  trunk: 'Магистраль',
  riser: 'Стояк',
  branch: 'Ответвление',
  connection: 'Подводка'
}

interface SegmentRowProps {
  readonly segmentId: string
  readonly index: number
  readonly calcResult: SegmentCalcResult | undefined
  readonly isInMainCircuit: boolean
  /** D-18: глубина в дереве, для inline padding. */
  readonly depth?: number
  readonly hasChildren?: boolean
  readonly isCollapsed?: boolean
  readonly onToggleCollapsed?: () => void
  /** Tree lines: true если узел последний среди своих siblings. */
  readonly isLastSibling?: boolean
  /** Для каждого предка (depth 0..depth-1) — был ли тот предок последним среди своих siblings. */
  readonly ancestorIsLast?: readonly boolean[]
}

export function SegmentRow({
  segmentId,
  index,
  calcResult,
  isInMainCircuit,
  depth = 0,
  hasChildren = false,
  isCollapsed = false,
  onToggleCollapsed,
  isLastSibling = true,
  ancestorIsLast = []
}: SegmentRowProps) {
  const [isExpanded, setIsExpanded] = useState(false)
  const [showKmsPicker, setShowKmsPicker] = useState(false)
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false)

  const segment = useSegmentStore(s => s.segments[segmentId])
  const allSegments = useSegmentStore(s => s.segments)
  const updateSegment = useSegmentStore(s => s.updateSegment)
  const deleteSegment = useSegmentStore(s => s.deleteSegment)

  const equipmentMap = useEquipmentStore(useShallow(s => s.equipment))
  const equipmentOrder = useEquipmentStore(useShallow(s => s.equipmentOrder))
  const rooms = useProjectStore(useShallow(s => s.rooms))
  const catalogModels = useCatalogStore(s => s.models)

  // Room dropdown: уникальные комнаты, в которых есть приборы.
  const roomOptions = useMemo(() => {
    const roomsWithEquipment = new Set<string>()
    for (const eqId of equipmentOrder) {
      const eq = equipmentMap[eqId]
      if (eq?.roomId) roomsWithEquipment.add(eq.roomId)
    }
    return [...roomsWithEquipment]
      .map(rid => rooms[rid])
      .filter((r): r is NonNullable<typeof r> => Boolean(r))
      .map(r => ({
        id: r.id,
        label: [r.number ? `пом. ${r.number}` : '', r.name, `${r.floor} этаж`]
          .filter(Boolean)
          .join(' · ')
      }))
  }, [equipmentOrder, equipmentMap, rooms])

  // Сейчас привязанная комната (через equipment.roomId).
  const boundRoomId = useMemo(() => {
    if (!segment?.equipmentId) return ''
    return equipmentMap[segment.equipmentId]?.roomId ?? ''
  }, [segment?.equipmentId, equipmentMap])

  // Приборы в выбранной комнате — для второго dropdown'а.
  const equipmentInRoom = useMemo(() => {
    if (!boundRoomId) return []
    return equipmentOrder
      .map(eid => equipmentMap[eid])
      .filter((eq): eq is NonNullable<typeof eq> => eq != null && eq.roomId === boundRoomId)
      .map(eq => ({
        id: eq.id,
        label: buildEquipmentModelName(eq, catalogModels) || 'Ручной прибор'
      }))
  }, [boundRoomId, equipmentOrder, equipmentMap, catalogModels])

  // Parent dropdown options: same-system only, исключая self (B3 path B).
  const parentOptions = useMemo(() => {
    if (!segment) return [] as Segment[]
    return Object.values(allSegments).filter(
      s => s.systemId === segment.systemId && s.id !== segment.id
    )
  }, [allSegments, segment])

  if (!segment) return null

  const zebraClass = index % 2 === 0 ? 'bg-[var(--color-bg)]' : 'bg-[var(--color-surface)]'
  const rowClass = isInMainCircuit
    ? 'bg-[var(--gck-bg)] border-l-4 border-l-[var(--gck-strip)]'
    : zebraClass

  // D-02: Q auto если equipmentId есть и нет qOverride
  const qIsAuto = segment.equipmentId !== null && segment.qOverride === null

  const handleDelete = () => {
    setShowDeleteConfirm(false)
    deleteSegment(segmentId)
  }

  const handleParentChange = (newParentId: string) => {
    const accepted = updateSegment(segmentId, {
      parentSegmentId: newParentId === '' ? null : newParentId
    })
    // Toast на cross-system reject вызывается из store (B3 path B: единый источник).
    void accepted
  }

  // Tree-lines: рисуем вертикальные/горизонтальные соединители между parent-child,
  // чтобы структура дерева была видна визуально (└─ ├─ │).
  // Каждый уровень — inline-block шириной 16px, monospace.
  const treeLines: React.ReactNode[] = []
  for (let i = 0; i < depth; i++) {
    if (i < depth - 1) {
      // Continuation column: если у предка на этом уровне есть ещё siblings ниже — рисуем │
      const ancestorWasLast = ancestorIsLast[i] ?? true
      treeLines.push(
        <span
          key={`line-${i}`}
          aria-hidden="true"
          className="inline-block w-4 font-mono text-center text-[var(--color-text-secondary)] opacity-60 select-none"
        >
          {ancestorWasLast ? '\u00A0' : '│'}
        </span>
      )
    } else {
      // Branch column (на уровне родителя): └─ для последнего, ├─ для остальных
      treeLines.push(
        <span
          key={`line-${i}`}
          aria-hidden="true"
          className="inline-block w-4 font-mono text-center text-[var(--color-text-secondary)] opacity-70 select-none"
        >
          {isLastSibling ? '└' : '├'}
        </span>
      )
    }
  }

  return (
    <>
      <tr
        className={`h-10 cursor-pointer hover:bg-[var(--color-surface)] ${rowClass}`}
        onClick={() => setIsExpanded(v => !v)}
        aria-expanded={isExpanded}
        data-gck={isInMainCircuit ? 'true' : undefined}
        data-depth={depth}
      >
        <td className="px-2 py-1" style={{ paddingLeft: 8 }}>
          <div className="flex items-center gap-1">
            {treeLines}
            {hasChildren ? (
              <button
                type="button"
                onClick={e => {
                  e.stopPropagation()
                  onToggleCollapsed?.()
                }}
                className="text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)]"
                aria-label={isCollapsed ? 'Развернуть' : 'Свернуть'}
              >
                <ChevronRight
                  size={12}
                  aria-hidden="true"
                  className={`transition-transform duration-150 ${isCollapsed ? '' : 'rotate-90'}`}
                />
              </button>
            ) : (
              <span className="inline-block w-3" />
            )}
            <SegmentKindIcon kind={segment.kind} />
            <ChevronRight
              size={12}
              aria-hidden="true"
              className={`transition-transform duration-200 text-[var(--color-text-secondary)] ${
                isExpanded ? 'rotate-90' : ''
              }`}
            />
          </div>
        </td>
        <td className="text-center font-mono text-xs text-[var(--color-text-secondary)]">
          {index + 1}
        </td>
        <td className="px-2 py-1">
          <div className="flex items-center gap-2">
            {/* Dropdown 1: помещение (в котором стоит прибор) */}
            <select
              value={boundRoomId}
              onClick={e => e.stopPropagation()}
              onChange={e => {
                const newRoomId = e.target.value
                if (!newRoomId) {
                  updateSegment(segmentId, { equipmentId: null })
                  return
                }
                // Авто-выбор первого прибора в выбранной комнате
                const firstEq = equipmentOrder
                  .map(eid => equipmentMap[eid])
                  .find(eq => eq?.roomId === newRoomId)
                updateSegment(segmentId, { equipmentId: firstEq?.id ?? null })
              }}
              className={`${INPUT_CLASS} w-44 shrink-0`}
              aria-label="Помещение"
              title="Помещение, в которое подходит этот участок"
            >
              <option value="">— свободный —</option>
              {roomOptions.map(opt => (
                <option key={opt.id} value={opt.id}>{opt.label}</option>
              ))}
            </select>

            {/* Dropdown 2: прибор в выбранной комнате (если есть больше одного — даём выбор) */}
            {boundRoomId && equipmentInRoom.length > 0 ? (
              <select
                value={segment.equipmentId ?? ''}
                onClick={e => e.stopPropagation()}
                onChange={e => {
                  const v = e.target.value || null
                  updateSegment(segmentId, { equipmentId: v })
                }}
                className={`${INPUT_CLASS} flex-1 min-w-0`}
                aria-label="Прибор в помещении"
                title="Прибор, к которому подводит этот участок"
              >
                {equipmentInRoom.map(opt => (
                  <option key={opt.id} value={opt.id}>{opt.label}</option>
                ))}
              </select>
            ) : (
              <>
                <input
                  type="text"
                  defaultValue={LEGACY_NAME_PATTERN.test(segment.name) ? '' : segment.name}
                  onClick={e => e.stopPropagation()}
                  onBlur={e => updateSegment(segmentId, { name: e.target.value.trim() })}
                  className={`${INPUT_CLASS} flex-1 min-w-0`}
                  aria-label="Назначение участка"
                  placeholder={`Участок №${index + 1} — напр.: магистраль, стояк`}
                />
                {segment.name && !LEGACY_NAME_PATTERN.test(segment.name) && (
                  <span className="sr-only" aria-hidden="true">{segment.name}</span>
                )}
              </>
            )}
            {segment.autoGenerated && (
              <span className="text-[10px] uppercase tracking-wide text-[var(--color-text-secondary)] border border-[var(--color-border)] rounded px-1 py-0.5">
                Автосгенерировано
              </span>
            )}
          </div>
        </td>
        <td className="text-right px-2 font-mono text-xs">
          {qIsAuto ? (
            <span className="text-[var(--color-text-secondary)]">
              {calcResult?.qWatts != null && calcResult.qWatts > 0
                ? calcResult.qWatts.toFixed(0)
                : '—'}
            </span>
          ) : (
            <input
              type="number"
              defaultValue={segment.qOverride ?? 0}
              onClick={e => e.stopPropagation()}
              onBlur={e => updateSegment(segmentId, { qOverride: parseFloat(e.target.value) || null })}
              className={`${INPUT_CLASS} w-20 text-right font-mono`}
              aria-label="Q, Вт"
            />
          )}
        </td>
        <td className="text-right px-2 font-mono text-xs">
          <input
            type="number"
            step="0.1"
            defaultValue={segment.lengthM}
            onClick={e => e.stopPropagation()}
            onBlur={e => updateSegment(segmentId, { lengthM: parseFloat(e.target.value) || 0 })}
            className={`${INPUT_CLASS} w-16 text-right font-mono`}
            aria-label="Длина участка, м"
          />
        </td>
        <td className="text-right px-2 font-mono text-xs">
          {formatDiameter(calcResult?.selectedPipe?.innerDiameterMm ?? null)}
        </td>
        <td className="text-right px-2 font-mono text-xs">
          {formatVelocity(calcResult?.velocityMS ?? 0)}
        </td>
        <td className="text-right px-2 font-mono text-xs font-semibold">
          {formatDeltaP(calcResult?.deltaPTotalPa ?? 0)}
        </td>
        <td className="text-center px-2">
          <button
            type="button"
            onClick={e => { e.stopPropagation(); setShowDeleteConfirm(true) }}
            className="text-[var(--color-destructive)] hover:underline text-xs"
            aria-label="Удалить участок"
          >
            ✕
          </button>
        </td>
      </tr>

      {isExpanded && (
        <tr>
          <td colSpan={9} className="p-0">
            <div className="p-3 border-t border-[var(--color-border)] bg-[var(--color-surface)] flex flex-col gap-3">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <label className="flex flex-col gap-1 text-xs">
                  <span className="text-[var(--color-text-secondary)]">Тип участка</span>
                  <select
                    value={segment.kind}
                    onChange={e => updateSegment(segmentId, { kind: e.target.value as Segment['kind'] })}
                    className={INPUT_CLASS}
                    aria-label="Тип участка"
                  >
                    {(['trunk', 'riser', 'branch', 'connection'] as const).map(k => (
                      <option key={k} value={k}>{KIND_LABELS[k]}</option>
                    ))}
                  </select>
                </label>

                <label className="flex flex-col gap-1 text-xs">
                  <span className="text-[var(--color-text-secondary)]">Родитель</span>
                  <select
                    value={segment.parentSegmentId ?? ''}
                    onChange={e => handleParentChange(e.target.value)}
                    className={INPUT_CLASS}
                    aria-label="Родительский сегмент"
                  >
                    <option value="">— (нет, корневой)</option>
                    {parentOptions.map(p => (
                      <option key={p.id} value={p.id}>{p.name || p.id.slice(-4)}</option>
                    ))}
                  </select>
                  <span className="text-[var(--color-text-secondary)] mt-0.5">
                    Родитель — только сегменты этой системы
                  </span>
                </label>
              </div>

              <TopologyWarnings segmentId={segmentId} />

              <SegmentDetails
                segment={segment}
                calcResult={calcResult}
                onOpenKmsPicker={() => setShowKmsPicker(true)}
              />
            </div>
          </td>
        </tr>
      )}

      {showKmsPicker && (
        <KmsPicker
          segmentId={segmentId}
          open={showKmsPicker}
          onClose={() => setShowKmsPicker(false)}
        />
      )}

      <ConfirmDialog
        open={showDeleteConfirm}
        title={`Удалить участок «${segment.name || segment.id.slice(-4)}»?`}
        message="Все данные участка потеряются. Дочерние сегменты останутся без родителя."
        confirmLabel="Удалить"
        cancelLabel="Отмена"
        variant="destructive"
        onConfirm={handleDelete}
        onCancel={() => setShowDeleteConfirm(false)}
      />
    </>
  )
}
