/**
 * RED scaffold: useGckPath(systemId) — per-system signature test.
 * Tests the pure logic/signature requirements for Task 1.
 *
 * Tests verify:
 *   - useGckPath accepts a systemId argument
 *   - early return (empty result) when systemId is empty string
 *   - filters segments by systemId before computation
 */

import { describe, it, expect } from 'vitest'

// We test only the type-level signature expectations via static import check
// and the filterSegmentsBySystem helper which is the key new export from hydraulics

import { filterSegmentsBySystem } from '../../engine/hydraulics'
import type { Segment } from '../../types/hydraulics'

function makeSeg(id: string, systemId: string): Segment {
  return {
    id,
    systemId,
    parentSegmentId: null,
    name: id,
    equipmentId: null,
    qOverride: null,
    lengthM: 5,
    pipeId: 'steel-vgp-dn20',
    dnMm: null,
    kmsCounts: {},
    velocityTargetMS: 0.6,
    kind: 'trunk',
    autoGenerated: false
  } as unknown as Segment
}

describe('filterSegmentsBySystem', () => {
  it('returns only segments matching systemId', () => {
    const segments: Record<string, Segment> = {
      'seg-a': makeSeg('seg-a', 'sys-1'),
      'seg-b': makeSeg('seg-b', 'sys-2'),
      'seg-c': makeSeg('seg-c', 'sys-1')
    }
    const result = filterSegmentsBySystem(segments, 'sys-1')
    expect(Object.keys(result)).toHaveLength(2)
    expect(Object.keys(result)).toContain('seg-a')
    expect(Object.keys(result)).toContain('seg-c')
    expect(Object.keys(result)).not.toContain('seg-b')
  })

  it('returns empty record when no segments match', () => {
    const segments: Record<string, Segment> = {
      'seg-a': makeSeg('seg-a', 'sys-1')
    }
    const result = filterSegmentsBySystem(segments, 'sys-unknown')
    expect(Object.keys(result)).toHaveLength(0)
  })

  it('returns empty record for empty segments input', () => {
    const result = filterSegmentsBySystem({}, 'sys-1')
    expect(Object.keys(result)).toHaveLength(0)
  })
})

// Type-level import test: useGckPath must accept a systemId argument
// This import will fail (type error) if useGckPath still has zero-argument signature
import { useGckPath } from './useGckPath'
describe('useGckPath signature', () => {
  it('useGckPath is exported and callable (type check only, not invoked outside React)', () => {
    // Function must exist and be callable with a string argument
    expect(typeof useGckPath).toBe('function')
    // Checking that the function accepts 1 argument (length check)
    expect(useGckPath.length).toBe(1)
  })
})
