/**
 * In-memory v1.0 store fixture for migration.test.ts unit tests.
 * These are TypeScript constants representing pre-04.1 store state:
 *   - No systemId on segments, equipment, ufhLoops
 *   - No systems / systemOrder
 *   - Global schemaType/pipeMaterialId/coolantId/tSupply/tReturn on project
 */

import type { Segment } from '../../types/hydraulics'
import type { Equipment } from '../../types/project'
import type { UfhLoop } from '../../types/hydraulics'

// V1.0 project-level fields (7 fields that will be moved to System in v1.1)
export const V10_PROJECT_STATE = {
  schemaVersion: '1.0',
  schemaType: 'two-pipe-dead-end',
  pipeMaterialId: 'steel-vgp-dn20',
  coolantId: 'water',
  tSupply: 80,
  tReturn: 60,
  tSupplyUfh: 45,
  tReturnUfh: 35
} as const

// V1.0 segments — without systemId, kind, autoGenerated
export const V10_SEGMENTS: Record<string, unknown> = {
  'seg-1': {
    id: 'seg-1',
    parentSegmentId: null,
    name: 'Магистраль',
    equipmentId: null,
    qOverride: null,
    lengthM: 10,
    pipeId: 'steel-vgp-dn20',
    dnMm: 20,
    kmsCounts: {},
    velocityTargetMS: 0.6
    // NO: systemId, kind, autoGenerated
  } as unknown as Segment,
  'seg-2': {
    id: 'seg-2',
    parentSegmentId: 'seg-1',
    name: 'Подводка к прибору',
    equipmentId: 'eq-1',
    qOverride: null,
    lengthM: 3,
    pipeId: 'steel-vgp-dn20',
    dnMm: 15,
    kmsCounts: { 'kms-elbow-90': 2 },
    velocityTargetMS: 0.3
    // NO: systemId, kind, autoGenerated
  } as unknown as Segment
}

export const V10_SEGMENT_ORDER = ['seg-1', 'seg-2'] as const

// V1.0 equipment — without systemId
export const V10_EQUIPMENT: Record<string, unknown> = {
  'eq-1': {
    id: 'eq-1',
    roomId: 'room-1',
    kind: 'bimetal',
    catalogModelId: 'rifar-base-500',
    connection: 'side',
    installation: 'open',
    panelType: null,
    panelHeightMm: null,
    panelLengthMm: null,
    sectionsOverride: null,
    convectorLengthMm: null,
    manualQNominal: null,
    manualNExponent: null
    // NO: systemId
  } as unknown as Equipment
}

// V1.0 UFH loops — without systemId
export const V10_UFH_LOOPS: Record<string, unknown> = {
  'loop-1': {
    id: 'loop-1',
    roomId: 'room-1',
    enabled: true,
    activeAreaM2: 16,
    covering: 'tile',
    pipeId: 'pe-x-dn16',
    stepCm: 15,
    leadInM: 3
    // NO: systemId
  } as unknown as UfhLoop
}
